"""Test all 44 clauses + a novel clause against the full pipeline."""
import sys
sys.path.insert(0, r"D:\ContractGuard")
from backend.agents.rule_engine import analyze_clause

# All 44 test cases
tests = [
    # test.txt (10)
    ("Payment Terms.", "Client shall pay all undisputed invoices within thirty (30) days of receipt. Any invoice not paid within such period shall accrue interest at a rate of 1.5% per month until paid in full.", False, "PAY01"),
    ("Payment Terms.", "Client shall pay all invoices within thirty (30) days of receipt. Any invoice not disputed in writing within five (5) business days of receipt shall be deemed irrevocably accepted. Interest on late balances shall accrue at the maximum rate permitted by law, compounded daily. Client agrees that all pricing is subject to automatic retroactive adjustments by Provider based on shifting operational overhead, and Client's payment obligations under this Section shall survive expiration or termination of this Agreement for a period of ten (10) years.", True, "PAY02"),
    ("Limitation of Liability.", "Except for breaches of confidentiality or indemnification obligations, neither party shall be liable to the other for any indirect, incidental, or consequential damages arising out of this Agreement.", False, "LIAB01"),
    ("Limitation of Liability.", "Except for Client's payment, confidentiality, and data safety obligations for which liability is completely uncapped neither party shall be liable to the other for indirect, incidental, or consequential damages. Provider's total aggregate liability for any and all claims, breaches, or negligence under this Agreement shall be strictly capped at fifty dollars ($50.00), regardless of the nature or severity of the underlying claim.", True, "LIAB02"),
    ("Term and Termination.", "This Agreement shall automatically renew for successive one-year terms unless either party provides written notice of non-renewal at least thirty (30) days prior to the end of the then-current term.", False, "REN01"),
    ("Term and Renewal.", "This Agreement shall automatically renew for successive three-year terms unless Client provides written notice of non-renewal via certified mail. Such notice must be received by Provider precisely between ninety (90) and eighty-five (85) days prior to the expiration of the current term. Failure to hit this window constitutes irrevocable acceptance of the renewal, along with an automatic, non-negotiable 25% price increase for the subsequent term.", True, "REN02"),
    ("Indemnification.", "Provider agrees to indemnify and hold harmless Client from any third-party claims arising directly from Provider's gross negligence or willful misconduct in performing the Services.", False, "IND01"),
    ("Indemnification.", "Client agrees to defend, indemnify, and hold harmless Provider and its affiliates from any and all claims, losses, or demands including reasonable attorney fees arising out of, relating to, or tangentially connected with the Services. Client's duty to defend arises immediately upon the mere allegation of a claim by any third party, regardless of whether any fault or liability on the part of the Client has been established by a court.", True, "IND02"),
    ("Intellectual Property.", "Each party retains all rights, title, and interest in its pre-existing intellectual property. Any deliverables created specifically for Client under this Statement of Work shall become the property of Client upon full payment of all underlying fees.", False, "IP01"),
    ("Intellectual Property.", "Client retains ownership of its pre-existing data. However, Client hereby grants Provider a worldwide, perpetual, irrevocable, royalty-free, transferable license to use, modify, exploit, and commercialize any data, feedback, or materials submitted to the platform. Any derivative works, workflows, or custom features developed during the term of this Agreement shall be the sole and exclusive property of Provider, even if funded entirely by Client.", True, "IP02"),
    # test2.txt (7)
    ("SECTION 1: SCOPE OF WORK", "Developer shall perform the software development services specified in Statement of Work (SOW) A. Any modifications to the scope of work must be agreed upon in a written amendment signed by both parties.", False, "T2_SCOPE"),
    ("SECTION 2: DELIVERY AND ACCEPTANCE", "Upon delivery of the software deliverables, Client shall have exactly forty-eight (48) hours to test and evaluate the software for defects. If Client does not reject the deliverables in writing within this forty-eight hour window, the software shall be deemed permanently and irrevocably accepted. Following acceptance, Developer is fully released from all performance obligations, bug fixes, or warranty claims, and Client waives all rights to withhold payment for any reason.", True, "T2_DELIV"),
    ("SECTION 3: PAYMENT TERMS", "Client shall pay Developer a fixed fee of $10,000 USD upon completion of the milestones outlined in the SOW. Invoices shall be paid within thirty (30) days of receipt.", False, "T2_PAY"),
    ("SECTION 4: INTELLECTUAL PROPERTY RIGHTS", "Developer retains sole and exclusive ownership of all source code, architecture, algorithms, and design elements created under this Agreement. Client is granted a non-transferable, revocable license to use the software solely for internal business operations. Developer reserves the right to terminate this license at any time, with or without cause, upon ten (10) days written notice, without obligation to refund any fees paid by Client.", True, "T2_IP"),
    ("SECTION 5: INDEMNIFICATION", "Developer agrees to indemnify Client against any third-party claims alleging that the deliverables infringe upon a valid United States patent or copyright, provided Client gives immediate notice of the claim.", False, "T2_IND"),
    ("SECTION 6: LIMITATION OF LIABILITY", "Developer's total liability for any breach, negligence, or system failure under this Agreement shall be limited to a maximum of one dollar ($1.00) USD. Client agrees to insulate, defend, and hold Developer harmless against any third-party lawsuits, operational losses, or regulatory fines that result directly from coding security flaws or vulnerabilities introduced by the Developer.", True, "T2_LIAB"),
    ("SECTION 7: SEVERABILITY", "If any provision of this Agreement is found to be invalid or unenforceable by a court of law, the remaining provisions shall continue in full force and effect.", False, "T2_SEV"),
    # test3.txt (7)
    ("SECTION 1: LICENSE GRANT", "Provider grants Client a non-exclusive, non-transferable right to access and use the Cloud Platform during the Subscription Term solely for its internal business operations.", False, "T3_LIC"),
    ("SECTION 2: DATA RIGHTS AND USE", "Client retains legal ownership of its uploaded data. However, Client hereby grants Provider a perpetual, worldwide, irrevocable, royalty-free license to mine, aggregate, monetize, and sell Client's operational data, user behaviors, and customer records to third-party data brokers. Provider is under no obligation to anonymize or de-identify this information prior to commercial distribution or public sale.", True, "T3_DATA"),
    ("SECTION 3: SERVICE LEVEL AGREEMENT", "Provider shall use commercially reasonable efforts to make the Cloud Platform available with a Monthly Uptime Percentage of at least 99.9% during any monthly billing cycle.", False, "T3_SLA"),
    ("SECTION 4: AUTOMATIC RENEWAL AND PRICING", "The initial subscription term is twelve (12) months. This Agreement will automatically renew for successive three-year terms unless Client cancels via certified mail exactly sixty-five (65) days before the expiration date. Failure to cancel precisely on this day triggers automatic renewal along with a compounding 50% increase in the annual subscription fee, which will be charged immediately to the Client's credit card on file without prior notification.", True, "T3_REN"),
    ("SECTION 5: CONFIDENTIALITY", "Each party agrees to protect the other party's confidential information with the same degree of care that it uses to protect its own confidential information of like kind, but no less than reasonable care.", False, "T3_CONF"),
    ("SECTION 6: TERMINATION FOR CONVENIENCE", "Provider may terminate this Agreement immediately at any time for any reason or no reason by cutting off account access. Client shall not be entitled to any refund for unused portions of prepaid subscription fees. Upon such termination, Provider reserves the right to permanently delete all Client data from its servers within one (1) hour, without providing a data export or backup copy to the Client.", True, "T3_TERM"),
    ("SECTION 7: GOVERNING LAW", "This Agreement shall be governed by and construed in accordance with the laws of the State of Delaware, without giving effect to any choice of law principles.", False, "T3_GOV"),
    # test4.txt (7)
    ("SECTION 1: DUTIES AND RESPONSIBILITIES", "Employee agrees to perform the duties customary to the position of Software Engineer. Employee shall report directly to the Engineering Manager and comply with all standard company policies, handbooks, and workplace guidelines.", False, "T4_DUTY"),
    ("SECTION 2: COMPENSATION AND BONUSES", "Employer shall pay Employee a base salary of $6,000 USD per month. However, Employee agrees that Employer reserves the right to retroactively reduce, withhold, or cancel any accrued salary, unpaid wages, or earned sales bonuses at its absolute discretion if Employer determines that Employee's monthly performance metrics fell below internal targets.", True, "T4_COMP"),
    ("SECTION 3: CONFIDENTIALITY", "Employee shall not disclose or use any of Employer's proprietary technical data, trade secrets, or client lists for personal gain or to the detriment of the company during or after the employment period.", False, "T4_CONF"),
    ("SECTION 4: COVENANT NOT TO COMPETE", "For a period of five (5) years following the termination of employment for any reason, Employee shall not directly or indirectly engage in, consult for, or establish any business that operates in the technology, software, or digital services sector anywhere within the continental United States. Employee acknowledges that this restriction applies even if Employee is terminated by Employer without cause during their probationary period.", True, "T4_NONCOMP"),
    ("SECTION 5: INTELLECTUAL PROPERTY PROVISIONS", "All inventions, software code, patents, and improvements developed by Employee during working hours or using company equipment shall be considered work-for-hire and remain the exclusive property of Employer.", False, "T4_IP"),
    ("SECTION 6: LIQUIDATED DAMAGES AND FEES", "If Employee terminates this Agreement prior to completing twenty-four (24) full months of service, Employee shall immediately pay Employer a lump sum liquidated damages penalty of twenty-five thousand dollars ($25,000.00) USD to offset recruitment and onboarding costs. Furthermore, Employee agrees to pay all of Employer's legal fees and court costs in any future dispute, regardless of which party ultimately prevails in the litigation.", True, "T4_LIQ"),
    ("SECTION 7: NOTICES", "Any notices required under this Agreement shall be sent in writing to the respective parties at the physical addresses listed in the introductory paragraph of this document.", False, "T4_NOT"),
    # test_novel.txt (10)
    ("1. Services.", "Provider will deliver the marketing services listed in Schedule A.", False, "NOV_SERV"),
    ("2. Payment and Fees.", "Provider will invoice Client monthly. All invoices are due within 15 days. Client may not dispute any invoice after 10 business days. Any unpaid amount will incur monthly interest at 3%. Provider may adjust fees at any time with 5 days email notice.", True, "NOV_PAY"),
    ("3. Intellectual Property.", "All deliverables, templates, methodologies, and work product created under this Agreement shall be the sole property of Provider. Client receives a non-exclusive, non-transferable license to use the deliverables for internal purposes only.", True, "NOV_IP"),
    ("4. Data License.", "Client retains ownership of its customer data. Client grants Provider a non-exclusive, worldwide, perpetual, irrevocable, sublicensable license to aggregate, analyze, and commercialize Client's customer data for any business purpose.", True, "NOV_DATA"),
    ("5. Limitation of Liability.", "Neither party shall be liable for indirect damages. Provider's maximum liability for any claim is the total fees paid by Client in the prior 6 months, not to exceed $100. This cap applies even if the Provider's negligence causes the loss.", True, "NOV_LIAB"),
    ("6. Indemnification.", "Client shall indemnify, defend, and hold Provider harmless from any third party claim arising out of Client's use of the services, including claims caused by Provider's own security failures or data breaches.", True, "NOV_IND"),
    ("7. Term and Renewal.", "This Agreement renews automatically each year. Client must send cancellation notice no earlier than 120 days and no later than 90 days before renewal. If Client fails to cancel within this window, the fees increase by 15%.", True, "NOV_REN"),
    ("8. Confidentiality.", "Each party will protect the other's confidential information for 3 years after termination.", False, "NOV_CONF"),
    ("9. Governing Law.", "This Agreement is governed by the laws of Delaware. Any disputes shall be resolved in the courts located in Provider's headquarters city.", False, "NOV_GOV"),
    ("10. Warranty Disclaimer.", "THE SERVICES ARE PROVIDED AS IS WITHOUT ANY WARRANTY. PROVIDER DISCLAIMS ALL IMPLIED WARRANTIES INCLUDING MERCHANTABILITY AND FITNESS.", True, "NOV_WAR"),
    # Vendor (3)
    ("SECTION 2: ALTERATIONS AND IMPROVEMENTS", "Vendor may make cosmetic adjustments to the space with prior approval. However, any physical improvements, light fixtures, shelving installations, or structural enhancements made by Vendor shall instantly become the permanent property of Property Owner. Upon expiration of this Agreement, Property Owner may compel Vendor to pay for the professional removal of these items, using a contractor exclusively selected by Property Owner at un-capped commercial rates.", True, "VEND_ALTER"),
    ("SECTION 4: OPERATIONAL FEES AND UTILITY SURCHARGES", "Vendor shall pay a flat monthly utility fee of $200 USD. Vendor agrees that Property Owner retains the right to levy unannounced, retroactive operational surcharges at any time to cover building repairs, HVAC overages, or property tax increases incurred over the prior three years. These surcharges are due within twenty-four (24) hours of electronic notice, and failure to pay grants Property Owner the right to seize Vendor's physical inventory as collateral.", True, "VEND_FEES"),
    ("SECTION 6: INDEMNIFICATION AND LANDLORD LIABILITY", "Vendor agrees to indemnify, protect, and absolve Property Owner from any liability relating to roof leaks, electrical fires, flooding, or building structural collapses, even if caused directly by Property Owner's failure to maintain the facilities. Vendor explicitly waives all claims for lost retail revenue, damaged inventory, or physical injuries suffered by employees due to property defects or lack of facility maintenance.", True, "VEND_INDEM"),
]

# A truly novel clause using completely different wording
novel_extra = [
    ("Data Processing and Analytics", "The Service Provider shall process Customer Data in accordance with the Data Processing Schedule. Customer acknowledges that Provider may use aggregated anonymized data for product improvement. Customer shall not access, copy, or reverse engineer any analytical models or algorithms developed by Provider.", True, "NOVEL_AGGR_DATA"),
    ("Non-Solicitation", "For a period of two years after termination, Consultant shall not directly or indirectly solicit, induce, or attempt to induce any employee of the Company to terminate their employment. This restriction applies regardless of the reason for termination of this Agreement.", False, "NOVEL_NON_SOLICIT"),
    ("Right to Match", "If Developer receives a bona fide written offer from a third party that would result in a change of control, Company shall have the right of first refusal to match the terms of such offer within sixty days of written notice.", False, "NOVEL_ROFR"),
    ("Most Favored Customer", "Provider represents that the pricing and discounts provided to Customer under this Agreement are the most favorable pricing offered to any customer. If Provider offers more favorable terms to any other customer, Customer shall automatically receive the same terms.", False, "NOVEL_MFC"),
    ("Key Person Clause", "The services under this Agreement shall be personally performed by Dr. Jane Smith, Chief Scientist. If Dr. Smith is unable to perform the services for any reason, Customer may terminate this Agreement without penalty.", False, "NOVEL_KEYPERSON"),
]

all_tests = tests + novel_extra
passes = fails = 0
for heading, text, expected, label in all_tests:
    harmful, reason = analyze_clause(heading, text)
    ok = (harmful == expected)
    if ok:
        passes += 1
    else:
        fails += 1
        print(f"FAIL [{label}] expected={expected} got={harmful}")
        if reason:
            print(f"  reason: {reason}")
print(f"\n{passes}/{passes + fails} passed, {fails} failed")
